config/routes.rb
require 'api_constraints'
require 'sidekiq/web'
require 'admin_constraint'

Bento::Application.routes.draw do

  # ============================================================
  # USER ROUTES
  # ============================================================
  delete 'logout'            => 'sessions#destroy',     as: "logout"
  get 'login'                => 'sessions#new',         as: "login"
  get 'signup'               => 'registrations#new',    as: "signup"
  get 'profile'              => 'registrations#edit',   as: "profile"
  post 'profile'             => 'registrations#update', as: "update_profile"
  get 'paswords/:token/edit' => 'passwords#edit',       as: "change_password"
  resource :password, only: [:new, :create, :edit, :update]
  resources :registrations, except: [:index, :show, :destroy]
  resources :sessions

  # ============================================================
  # API ROUTES
  # ============================================================
  get '/stripe/callback'    => 'stripe#callback'
  get 'api/google_shopping' => 'api#google_shopping'
  get 'api/sitemap'         => 'api#sitemap'
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :products, only: [:index, :show]
    end
  end

  # ============================================================
  # ADMIN ROUTES
  # ============================================================
  scope module: 'admin', path: 'adm1nistr8tion', as: 'admin' do
    mount Sidekiq::Web => 'sidekiq', constraints: AdminConstraint.new
    root to: 'dashboard#show', as: :dashboard
    get 'search', to: 'dashboard#search',   as: :search
    get 'audit',  to: 'audit_trails#index', as: 'audit'
    resource :stock, only: [:show, :update], path: 'stocks', as: 'stocks'
    resources :articles
    resources :categories, only: [:index, :edit, :update, :destroy]
    resources :clients, only: [:index, :show] do
      get 'export', on: :collection
    end
    resources :coupons, except: :show
    resources :pages
    resources :taxes
    scope "/shipping" do
      root to: 'shipping_countries#index', as: :shipping
      resources :shipping_countries, except: [:index, :show]
    end

    resources :collections do
      member do
        post 'sort_products'
        post 'add_products'
        post 'remove_products'
      end
    end

    resources :resellers, only: [:index, :show] do
      get 'catalogue', on: :collection
      member do
        post :toggle_reseller_status
      end
    end

    resources :products do
      resource :options, only: [:edit, :update], as: :options
      resources :variants, only: [:destroy]
      collection do
        put 'feature'
        get 'export'
      end
      resources :pictures do
        collection do
          post :sort
        end
      end
    end

    resources :product_reviews, only: [:index, :show] do
      member do
        post :toggle_product_review_status
      end
    end

    resource :settings, only: [:show, :update] do
      delete :remove_logo
    end

    resource :reports do
      collection do
        get 'sales'
        get 'monthly_sales'
        get 'orders'
      end
    end

    resources :users, except: [:show, :edit, :update] do
      post :toggle_status, on: :member
    end

    resources :orders, only: [:index, :show, :edit, :update] do
      put 'print', on: :collection
      get 'abandoned', on: :collection
      member do
        post 'mark_as_shipped'
        post 'cancel'
      end
    end
  end

  # ============================================================
  # RESELLER ROUTES
  # ============================================================
  scope module: 'reseller', path: 'reseller', as: 'reseller' do
    root to: 'dashboard#show', as: :dashboard
    resources :carts, only: [:new, :update, :destroy]
    resources :orders, only: [:index, :show, :new, :create]
    resources :products do
      resource :options, only: [:edit, :update], as: :options
    end
  end

  # ============================================================
  # PUBLIC ROUTES
  # ============================================================
  post 'language/set_to_english'
  post 'language/set_to_french'
  get 'application/users' # used for dynamic caching only

  scope '/blog' do
    get '/', controller: 'articles', action: 'index', as: 'blog'
    get '/:slug'    => "articles#show",  as: 'article'
    get '/tag/:tag' => "articles#index", as: 'tag'
  end

  resource :cart, except: [:new, :create, :edit] do
    member do
      post :apply_coupon
      post :remove_coupon
      get :checkout
      post :continue
    end
    resources :line_items
  end
  resources :line_items, only: [:create, :update]

  resources :orders, only: [:index, :new, :create, :show]
  resources :tags, only: :index
  resources :categories, only: :index
  resources :suppliers, only: :index
  resources :product_reviews, only: :create
  resources :products, only: [:index, :show] do
    get :search, on: :collection
  end
  resources :shippings, only: [] do
    post :search, on: :collection
  end
  resource :reseller_request, only: :create
  resource :contact, only: [:show, :create]
  
  get '/category/:category', to: 'products#index',        as: 'category'
  get '/collection/:slug',   to: 'collections#show',      as: 'collection'
  get 'become_reseller',     to: 'pages#become_reseller', as: "become_reseller"
  get 'user_info',           to: 'pages#user_info'
  get 'set_currency',        to: 'application#set_currency'
  get 'get_total',           to: 'application#get_total'
  get '/:slug',              to: 'pages#show',            as: 'page'

  root :to => 'pages#home'
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  # SEARCH
  # ------------------------------------------------------------------------------------------------------
  include PgSearch
  multisearchable :against => [:first_name, :last_name, :email]
  pg_search_scope :search_by_keyword,
                  :against => [:first_name, :last_name, :email],
                  :using => {
                    :tsearch => {
                      :prefix => true # match any characters
                    }
                  },
                  :ignoring => :accents


  # ASSOCIATIONS
  # ------------------------------------------------------------------------------------------------------
  has_many :orders, foreign_key: 'client_id', dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :posts
  has_one  :reseller_request
  accepts_nested_attributes_for :reseller_request, reject_if: ->(rr) { rr[:location].blank? }, allow_destroy: true
  has_many :reviews, class_name: "ProductReview"
  has_many :addresses, as: :addressable, dependent: :destroy
  accepts_nested_attributes_for :addresses


  # SCOPES
  # ------------------------------------------------------------------------------------------------------
  scope :admin,            -> { where(admin: true) }
  scope :active,           -> { where(active: true) }
  scope :inactive,         -> { where(active: false) }
  scope :exclude_users,    -> (user_ids) { where("id NOT IN (?)", user_ids) }
  scope :normal,           -> { where(admin: false) }
  scope :active_resellers, -> { where(reseller: true) }
  scope :resellers,        -> { joins(:reseller_request) }
  scope :today,            -> { where("created_at BETWEEN '#{DateTime.now.beginning_of_day}' AND '#{DateTime.now.end_of_day}'") }
  scope :weekly,           -> { where(created_at: Time.now.beginning_of_week..Time.now.end_of_week) }
  scope :monthly,          -> { where(created_at: Time.now.beginning_of_month..Time.now.end_of_month) }


  # VALIDATIONS
  # ------------------------------------------------------------------------------------------------------
  validates_confirmation_of :password
  validates_presence_of :password, on: :create
  validates_presence_of :email, :first_name, :last_name
  validates_uniqueness_of :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/
  validates_length_of :password, minimum: 6, if: :password
  validates_confirmation_of :password, if: :password


  # CALLBACKS
  # ------------------------------------------------------------------------------------------------------
  before_create :format_fields


  # INSTANCE METHODS
  # ------------------------------------------------------------------------------------------------------
  def full_name
    "#{first_name} #{last_name}"
  end

  def email_helper
    "#{full_name} <#{email}>"
  end

  def self.to_csv(options = {})
    headers = %w{Email FirstName LastName}
    header_indexes = Hash[headers.map.with_index{|*x| x}]

    CSV.generate(options) do |csv|
      csv << headers
      all.each do |client|
        data = {}
        data["Email"] = client.email
        data["FirstName"] = client.first_name
        data["LastName"] = client.last_name

        row = []
        header_indexes.each do |field, index|
          row << data[field] || ''
        end
        csv << row
      end
    end
  end

  def toggle_status
    self.active = !active
    save!
  end

  def toggle_reseller_status
    self.reseller = !self.reseller
    self.reseller_request.approved = !self.reseller_request.approved
    save!
  end

  def active_reseller?
    reseller_request.present? && reseller_request.approved?
  end

  private

    def format_fields
      self.email = email.downcase
      self.first_name = first_name.titleize
      self.last_name = last_name.titleize
    end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  before_action :set_order, only: [:update, :mark_as_shipped, :cancel]
  set_tab :orders
  helper_method :sort_column, :sort_direction

  def index
    @orders = Order.includes(:client).order(sort_column + " " + sort_direction).page(params[:page]).per(20)
    @orders = @orders.where(id: params[:order_ids]) if params[:order_ids].present?

    respond_to do |format|
      format.html
      format.pdf do
        pdf = OrdersPdf.new(@orders)
        send_data pdf.render, filename: "#{t 'order'}.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  def show
    @order = Order.includes(:client, :audits, :shipping_address, :billing_address).find(params[:id])

    respond_to do |format|
      format.html
      format.pdf do
        pdf = OrdersPdf.new([@order])
        send_data pdf.render, filename: "#{t 'order'} ##{@order.code}.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  def edit
    @order = Order.includes(:shipping_address, :billing_address).find(params[:id])
  end

  def update
    respond_to do |format|
      if @order.update_attributes(safe_params)
        format.html { redirect_to admin_order_url(@order), notice: 'Order was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def mark_as_shipped
    @order.ship(current_user)

    respond_to do |format|
      if @order.errors.blank?
        format.html { redirect_to admin_order_url(@order), notice: 'Order shipped.' }
        format.js
      else
        format.html { render action: "index", notice: 'An error occured. Please try again.' }
        format.js
      end
    end
  end

  def cancel
    @order.cancel(current_user)

    respond_to do |format|
      if @order.errors.blank?
        format.html { redirect_to admin_order_url(@order), notice: 'Order cancelled.' }
        format.js
      else
        format.html { render action: "index", notice: 'An error occured. Please try again.' }
        format.js
      end
    end
  end

  def print
    # find by id: params[:order_ids]
    # send to pdf
  end

  def abandoned
    @carts = Cart.with_items.includes(:items).page(params[:page]).per(20)
  end

  private

    def safe_params
      params.require(:order).permit(:state, :shipped_at, 
                                    shipping_address_attributes: [:id, :address1, :address2, :city, :country, :postal_code, :province],
                                    billing_address_attributes: [:id, :address1, :address2, :city, :country, :postal_code, :province] )
    end

    def set_order
      @order = Order.find(params[:id])
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end

    def sort_column
      Order.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :require_login, only: [:index, :show]

  def index
  	@orders = current_user.orders.regular.order('created_at DESC')
  end

	def new
		@cart = current_cart
    @currency = session[:currency]

    if @cart.items.empty?
      redirect_to products_url, notice: "#{t 'cart.is_empty', default: 'Cart is empty'}."
      return
    end

    @shipping_country = ShippingCountry.find_by_country(@cart.shipping_address.country) || ShippingCountry.find_by_country('WORLDWIDE')
    shipping_rates = (@shipping_country && @shipping_country.rates.order('price ASC')) || []

    # TODO: add weight check
    @applicable_rates = shipping_rates.select {|shipping_rate| shipping_rate.criteria == 'price-based' && @cart.subtotal >= shipping_rate.min_criteria }

    @shipping_estimate = ShippingRate.estimate(@cart.subtotal, @applicable_rates)

    @order = Order.new
    @order.build_from_cart(@cart, @shipping_country, @shipping_estimate)

    unless @shipping_country
      flash.now.alert = "#{t 'theme.cart.no_shipping_in_country', default: 'Sorry, we cannot proceed with your order as we currently do not ship to'} #{Country[@cart.shipping_address.country].name}"
    end
	end

	def create
    @cart = current_cart
		@order = Order.new(safe_params)
    @order.client_id = current_user.id if current_user
    @order.remote_ip = request.remote_ip

    @shipping_country = ShippingCountry.find_by_country(@cart.shipping_address.country) || ShippingCountry.find_by_country('WORLDWIDE')
    @shipping_estimate = ShippingRate.find(params[:shipping_rate])
    @order.build_from_cart(@cart, @shipping_country, @shipping_estimate)
    @order.copy_from_cart(@cart)

    respond_to do |format|
      if @order.save_with_payment(@cart)
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        auto_login(@order.client) unless current_user
        StoreMailer.order_receipt(@order).deliver
        AdminMailer.new_order(@order).deliver

        begin
        WebhookWorker.perform_async(@order.id)
        rescue => e
          logger.error "Sidekiq error while perform_async order: #{@order.code}, #{e.message}"
          flash[:error] = "An error occured."
          format.html { redirect_to @order, notice: "#{t 'theme.orders.thank_you', default: 'Thank you for your order'}." }
        end

        format.html { redirect_to @order, notice: "#{t 'theme.orders.thank_you', default: 'Thank you for your order'}." }
      else
        flash[:error] = "An error occured."
        format.html { redirect_to action: "new" }
      end
    end
	end

	def show
		@order = current_user.orders.find(params[:id])
	end

  private

    def safe_params
      params.require(:order).permit(:stripe_card_token)
    end

end

app/views/admin/orders/_audits.html.erb
<% if @order.audits.any? %>
  <h4 style="padding-top:20px; clear:both;"><%= t 'history' %></h4>

  <table class="table table-striped">
    <tr>
    	<th></th>
      <th><%= t 'event' %></th>
      <th><%= Date %></th>
    </tr>
    
    <% @order.audits.order('created_at DESC').each do |audit_trail| %>
      <tr>
      	<td>
      		<% if audit_trail.success? %>
      		  <%= status_tag "#{t 'success'}", class: "label label-success" %>
      		<% else %>
      		  <%= status_tag "#{t 'error'}", class: "label label-error" %>
      		<% end %>
      	</td>
        <td>
          <%= audit_trail.message.titleize %> <%= "#{t 'by'} #{audit_trail.user.first_name}" if audit_trail.user_id.present? %>
          <% if audit_trail.message == "open" %> - <%= "#{t 'payment_received_with_card_ending'} ##{@order.last4}" %><% end %>
        </td>
        <td><%= l audit_trail.created_at, format: :long %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/admin/orders/_items.html.erb
<table class="table table-striped" style="margin-top:20px;" >
  <tr id="table-headers">
  	<th>Item</th>
  	<th>Price</th>
    <th>Quantity</th>
    <th>Subtotal</th>
  </tr>

  <% @order.items.each do |item| %>
    <tr>
    	<td><%= item.product.name %> <% if item.product_variant_id.present? %>(<b><%= item.variant.name %></b>)<% end %></td>
    	<td><%= number_to_currency(item.price) %></td>
      <td><%= item.quantity %></td>
      <td><%= number_to_currency(item.subtotal) %></td>
    </tr>
  <% end %>
  <tr class="total">
    <th colspan="3" style="text-align:right;">Subtotal</th>
    <th><%= number_to_currency(@order.subtotal) %></th>
  </tr>
  <tr class="total">
    <th colspan="3" style="text-align:right;">Total</th>
    <th><%= number_to_currency(@order.total) %></th>
  </tr>
</table>

app/views/admin/orders/_map.html.erb
<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
  var geocoder;
  var map;

  function initialize() {
    geocoder = new google.maps.Geocoder();
    var latlng = new google.maps.LatLng(-34.397, 150.644);
    var mapOptions = {
      zoom: 14,
      center: latlng,
      disableDefaultUI: true,
      zoomControl: true,
      zoomControlOptions: {
        style: google.maps.ZoomControlStyle.SMALL
      },
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
  }

  function codeAddress() {
    var address = "<%= @order.shipping_address.render_map %>"
    geocoder.geocode( { 'address': address}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        map.setCenter(results[0].geometry.location);
        var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
      } else {
      alert("Geocode was not successful for the following reason: " + status);
      }
    });
  }

  window.onload = function() {
    initialize();
    codeAddress();
  }
</script>

app/views/admin/orders/_order.html.erb
<%= content_tag_for :tr, order do %>
  <td><%= check_box_tag "order_ids[]", order.id %></td>
  <td><%= link_to order.code, admin_order_path(order) %></td>
  <td><%= status_tag(order.state, class: "state-#{order.state}") %></td>
  <td><%= order.client.full_name %></td>
  <td><%= l order.created_at, format: :long %></td>
  <td><%= order.shipping_method %> (<%= order.shipping_address.country %>)</td>
  <td><%= number_to_currency(order.total, strip_insignificant_zeros: true) %></td>
  <td>
    <% if order.open? %>
      <%= icon_button_link_to "#{t 'status.mark_as_shipped'}", mark_as_shipped_admin_order_path(order), method: :post, remote: true, icon: 'ok', level: 'info', data: {disable_with: "#{t 'status.mark_as_shipped'}"} %>
    <% elsif order.shipped? %>
      <%= "#{t 'shipped_on'}" %> <%= l order.shipped_at, format: "%d %b %H:%m" if order.shipped? %>
    <% end %>
  </td>
<% end %>

app/views/admin/orders/abandoned.html.erb
<%= page_title("Abandoned checkouts") %>

<% if @carts.present? %>
  <table id="orders" class="table table-striped">
	  <tr id="table-headers">
	  	<th><%= sortable "created_at", "Date" %></th>
	  	<th><%= sortable "reminded", "Email status" %></th>
	  	<th>Items</th>
	  	<th><%= sortable "total", "#{t 'total'}" %></th>
	    <th><%= sortable "coupon_code", "Coupon" %></th>
	    <th><%= sortable "email" %></th>
	    <th><%= sortable "full_name", "#{t 'client'}" %></th>
	  </tr>

	  <% @carts.each do |cart| %>
	    <tr>
	      <td><%= l cart.created_at, format: :long %></td>
	      <td><%= status_tag("#{cart.reminded? ? 'Sent' : 'Not sent'}", level: "#{cart.reminded? ? 'warning' : ''}") %></td>
	      <td><% if cart.items.length > 0 %>
	        <%= link_to cart.items.length, "#", class: 'popover1', data: {toggle: "popover", title: pluralize(cart.items.length, 'item'), content: "#{cart.items.map{|i| i.summary}.to_sentence}"} %>
	      <% else %>
	        0
	      <% end %></td>
	      <td><%= number_to_currency(cart.total) %></td>
	      <td><%= cart.coupon_code %></td>
	      <td><%= cart.user.present? ? cart.user.email : cart.email %></td>
	      <td><%= cart.user.present? ? cart.user.try(:full_name) : "#{cart.first_name} #{cart.last_name}" %></td>
	    </tr>
	  <% end %>
	</table>
<% else %>
  <p class="alert">No abandoned checkouts found.</p>
<% end %>

<%= paginate @carts %>

<script>
  $(document).ready(function() {
    $(".popover1").popover();
  });
</script>

app/views/admin/orders/edit.html.erb
<%= page_title("Editing ##{@order.code}") %>

<%= simple_form_for([:admin, @order], html: {class: 'form-horizontal'}) do |f| %>
  <%= f.error_notification %>
  <div class="row-fluid">
    <div class="span6 address billing">
      <h4><%= t 'shipping_address' %></h4>
      <%= f.fields_for :shipping_address do |ff| %>
        <%= ff.input :full_name %>
        <%= ff.input :address1 %>
        <%= ff.input :address2 %>
        <%= ff.input :city %>
        <%= ff.input :postal_code %>
        <%= ff.input :country, collection: all_countries %>
        <%= ff.input :province, collection: province_options, as: :grouped_select, group_method: :last, group_label_method: :first, wrapper_html: {id: 'shipping_province'} %>
      <% end %>
    </div>

    <div class="span6 address shipping">
      <h4><%= t 'billing_address' %></h4>
      <%= f.fields_for :billing_address do |ff| %>
        <%= ff.input :full_name %>
        <%= ff.input :address1 %>
        <%= ff.input :address2 %>
        <%= ff.input :city %>
        <%= ff.input :postal_code %>
        <%= ff.input :country, collection: all_countries %>
        <%= ff.input :province, collection: province_options, as: :grouped_select, group_method: :last, group_label_method: :first, wrapper_html: {id: 'billing_province'} %>
      <% end %>
    </div>
  </div>

  <div class="form-actions">
    <%= submit_or_cancel(f) %>
  </div>
<% end %>

app/views/admin/orders/index.html.erb
<%= page_title("#{t 'orders.title'}") do %>
  <%= link_to "Abandoned checkouts", abandoned_admin_orders_path, class: 'pull-right btn btn-default' %>
<% end %>

<% if @orders.present? %>
  <%= form_tag params.merge(format: :pdf), method: :get do %>
    <div class="well well-small">
    	<%= submit_tag "Print invoices", class: "btn btn-inverse", name: nil %>
    </div>

	  <table id="orders" class="table table-striped">
		  <tr id="table-headers">
		  	<th></th>
		    <th><%= sortable "code", "#" %></th>
		    <th><%= sortable "completed", "#{t 'status.title'}" %></th>
		    <th><%= sortable "client.full_name", "#{t 'client'}" %></th>
		    <th><%= sortable "created_at", "Date" %></th>
		    <th>Shipping</th>
		    <th><%= sortable "total", "#{t 'total'}" %></th>
		    <th></th>
		  </tr>

		  <% @orders.each do |order| %>
		    <%= render order %>
		  <% end %>
		</table>

	  <%= paginate @orders %>
	<% end %>
<% else %>
  <div class="alert"><%= t 'orders.none' %>.</div>
<% end %>

app/views/admin/orders/mark_as_shipped.js.erb
<% if @order.errors.any? %>
  alert(<%= j @order.errors.full_messages.to_sentence %>);
<% else %>
  $("#<%= dom_id(@order) %>").replaceWith($('<%= j(render(@order)) %>'));
<% end %>

app/views/admin/orders/show.html.erb
<%= page_title("##{@order.code}") do %>
  <%= status_tag(@order.state, class: "state-#{@order.state}") %>
  <%= status_tag("#{t 'recovered'}", level: "success") if @order.recovered? %> <span id='order_date'> <%= l @order.created_at, format: :long %></span>
  <div class="btn-group fr">
    <%= icon_button_link_to "#{t 'edit'}", edit_admin_order_path(@order), icon: "pencil" %></td>
    <%= icon_button_link_to "#{t 'print'}", admin_order_path(@order, format: :pdf), icon: "print" %></td>
    <%= icon_button_link_to "#{t 'status.mark_as_shipped'}", mark_as_shipped_admin_order_path(@order), method: :post, confirm: "#{t 'are_you_sure'}", level: 'primary', white: true, icon: "ok" if @order.open? %></td>
    <%= icon_button_link_to "#{t 'cancel'}", cancel_admin_order_path(@order), method: :post, confirm: "#{t 'are_you_sure'}", level: 'danger', white: true, icon: "remove" if @order.open? %></td>
  </div>
<% end %>

<% if @order.pending? %>
  <div class="progress progress-danger progress-striped active">
    <div class="bar" style="width:100%;"><%= t 'status.not_paid' %></div>
  </div>
<% end %>

<h3>
  <%= @order.client.full_name %> (<%= mail_to @order.client.email, @order.client.email %>)
  <% if @order.shipped? %><span class="fr normal-text"><%= t 'shipped_on' %> <%= l @order.shipped_at, format: :long %></span><% end %>
</h3>

<%= render 'orders/items' %>

<% if @order.coupon_code.present? %>
  <p>
    <b><%= t 'coupon_code' %>:</b> <%= @order.coupon_code %>
  </p>
<% end %>

<div id="addresses" class="row-fluid">
  <div class="span4 address billing">
    <address>
      <strong><p><%= t 'billing_address' %></strong></p>
      <p><%= @order.client.full_name %></p>
      <%= @order.billing_address.display_name %>
    </address>
  </div>

  <div class="span8 address shipping">
    <div class="span6">
      <address>
        <strong><p><%= t 'shipping_address' %></strong> <span class="shipping_method">(<%= @order.shipping_method %>)</span></p>
        <p><%= @order.client.full_name %></p>
        <%= @order.shipping_address.display_name %>
      </address>
    </div>

    <div class="span6">
      <div id="map-canvas" style="width:348px; height:140px;"></div>
    </div>
  </div>
</div>

<%= render 'audits' %>
<%= render 'map' %>