config/routes.rb
require 'api_constraints'
require 'sidekiq/web'
require 'admin_constraint'

Bento::Application.routes.draw do

  # ============================================================
  # USER ROUTES
  # ============================================================
  delete 'logout'            => 'sessions#destroy',     as: "logout"
  get 'login'                => 'sessions#new',         as: "login"
  get 'signup'               => 'registrations#new',    as: "signup"
  get 'profile'              => 'registrations#edit',   as: "profile"
  post 'profile'             => 'registrations#update', as: "update_profile"
  get 'paswords/:token/edit' => 'passwords#edit',       as: "change_password"
  resource :password, only: [:new, :create, :edit, :update]
  resources :registrations, except: [:index, :show, :destroy]
  resources :sessions

  # ============================================================
  # API ROUTES
  # ============================================================
  get '/stripe/callback'    => 'stripe#callback'
  get 'api/google_shopping' => 'api#google_shopping'
  get 'api/sitemap'         => 'api#sitemap'
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :products, only: [:index, :show]
    end
  end

  # ============================================================
  # ADMIN ROUTES
  # ============================================================
  scope module: 'admin', path: 'adm1nistr8tion', as: 'admin' do
    mount Sidekiq::Web => 'sidekiq', constraints: AdminConstraint.new
    root to: 'dashboard#show', as: :dashboard
    get 'search', to: 'dashboard#search',   as: :search
    get 'audit',  to: 'audit_trails#index', as: 'audit'
    resource :stock, only: [:show, :update], path: 'stocks', as: 'stocks'
    resources :articles
    resources :categories, only: [:index, :edit, :update, :destroy]
    resources :clients, only: [:index, :show] do
      get 'export', on: :collection
    end
    resources :coupons, except: :show
    resources :pages
    resources :taxes
    scope "/shipping" do
      root to: 'shipping_countries#index', as: :shipping
      resources :shipping_countries, except: [:index, :show]
    end

    resources :collections do
      member do
        post 'sort_products'
        post 'add_products'
        post 'remove_products'
      end
    end

    resources :resellers, only: [:index, :show] do
      get 'catalogue', on: :collection
      member do
        post :toggle_reseller_status
      end
    end

    resources :products do
      resource :options, only: [:edit, :update], as: :options
      resources :variants, only: [:destroy]
      collection do
        put 'feature'
        get 'export'
      end
      resources :pictures do
        collection do
          post :sort
        end
      end
    end

    resources :product_reviews, only: [:index, :show] do
      member do
        post :toggle_product_review_status
      end
    end

    resource :settings, only: [:show, :update] do
      delete :remove_logo
    end

    resource :reports do
      collection do
        get 'sales'
        get 'monthly_sales'
        get 'orders'
      end
    end

    resources :users, except: [:show, :edit, :update] do
      post :toggle_status, on: :member
    end

    resources :orders, only: [:index, :show, :edit, :update] do
      put 'print', on: :collection
      get 'abandoned', on: :collection
      member do
        post 'mark_as_shipped'
        post 'cancel'
      end
    end
  end

  # ============================================================
  # RESELLER ROUTES
  # ============================================================
  scope module: 'reseller', path: 'reseller', as: 'reseller' do
    root to: 'dashboard#show', as: :dashboard
    resources :carts, only: [:new, :update, :destroy]
    resources :orders, only: [:index, :show, :new, :create]
    resources :products do
      resource :options, only: [:edit, :update], as: :options
    end
  end

  # ============================================================
  # PUBLIC ROUTES
  # ============================================================
  post 'language/set_to_english'
  post 'language/set_to_french'
  get 'application/users' # used for dynamic caching only

  scope '/blog' do
    get '/', controller: 'articles', action: 'index', as: 'blog'
    get '/:slug'    => "articles#show",  as: 'article'
    get '/tag/:tag' => "articles#index", as: 'tag'
  end

  resource :cart, except: [:new, :create, :edit] do
    member do
      post :apply_coupon
      post :remove_coupon
      get :checkout
      post :continue
    end
    resources :line_items
  end
  resources :line_items, only: [:create, :update]

  resources :orders, only: [:index, :new, :create, :show]
  resources :tags, only: :index
  resources :categories, only: :index
  resources :suppliers, only: :index
  resources :product_reviews, only: :create
  resources :products, only: [:index, :show] do
    get :search, on: :collection
  end
  resources :shippings, only: [] do
    post :search, on: :collection
  end
  resource :reseller_request, only: :create
  resource :contact, only: [:show, :create]
  
  get '/category/:category', to: 'products#index',        as: 'category'
  get '/collection/:slug',   to: 'collections#show',      as: 'collection'
  get 'become_reseller',     to: 'pages#become_reseller', as: "become_reseller"
  get 'user_info',           to: 'pages#user_info'
  get 'set_currency',        to: 'application#set_currency'
  get 'get_total',           to: 'application#get_total'
  get '/:slug',              to: 'pages#show',            as: 'page'

  root :to => 'pages#home'
end

app/models/cart.rb
class Cart < ActiveRecord::Base

  # ASSOCIATIONS
  # ------------------------------------------------------------------------------------------------------
  has_many :items, class_name: "LineItem", dependent: :destroy
  accepts_nested_attributes_for :items, reject_if: proc { |a| a['quantity'].to_i == 0 }, allow_destroy: true

  has_one :billing_address, as: :addressable, class_name: "BillingAddress", dependent: :destroy
  accepts_nested_attributes_for :billing_address

  has_one :shipping_address, as: :addressable, class_name: "ShippingAddress", dependent: :destroy
  accepts_nested_attributes_for :shipping_address

  belongs_to :user


  # ATTRIBUTES
  # ------------------------------------------------------------------------------------------------------
  attr_accessor :tax_amount


  # SCOPES
  # ------------------------------------------------------------------------------------------------------
  scope :not_reminded, -> { where(reminded: false) }
  scope :with_items,   -> { where("line_items_count > ?", 0) }


  # VALIDATIONS
  # ------------------------------------------------------------------------------------------------------
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/, allow_blank: true
  validate :validate_coupon_code_exists, if: :coupon_code?

  before_validation do |cart|
    if billing_address && billing_address.also_shipping_address
      if shipping_address
        shipping_address.copy(billing_address)
        shipping_address.bypass_validation = true
      end
    end
  end


  # INSTANCE METHODS
  # ------------------------------------------------------------------------------------------------------
  # buyable can be product or variant
  # return: line item
  def add_to_cart(variant)
    if variant.in_stock?
      current_item = items.where(variant_id: variant.id).first_or_initialize
      current_item.quantity += 1 unless current_item.new_record?
      current_item.price = variant.current_price
      current_item.save
      calculate
  	  current_item
    else
      I18n.t("theme.out_of_stock", default: "Out of Stock")
    end
  end

  def remove_from_cart(line_id)
    items.where(id: line_id).destroy_all
    calculate
  end

  def apply_coupon(code)
    begin
      coupon = Coupon.active.find_by_code!(code)
      self.coupon_code = code
      self.coupon_amount = coupon.amount
      self.coupon_percentage = coupon.percentage
      calculate
    rescue Exception => e
      puts e.message
      puts e.backtrace
      # if coupon does not valid, then remove it from cart
      remove_coupon
    end
  end

  def remove_coupon
    puts "remove_coupon"
    self.coupon_code = nil
    self.coupon_amount = nil
    self.coupon_percentage = nil
    calculate
  end

  def calculate
    self.subtotal = items.inject(0) { |sum, item| sum + item.subtotal }

    # discount
    self.total = subtotal - discount

    # shipping
    self.total += try(:shipping) || 0

    # tax
    @tax_amount = subtotal * ((try(:tax_rate) || 0) / 100)
    self.total += @tax_amount

    self.save
  end

  def discount
    if coupon_applied?
      if !!coupon_percentage
        (subtotal * ((coupon_amount || 0) / 100)).truncate(2)
      else
        coupon_amount || 0
      end
    else
      0
    end
  end

  def coupon_applied?
    coupon_code && coupon_amount
  end

  def shipping_availability?
    if shipping_address && shipping_address.country
      shipping_country = ShippingCountry.find_by_country(shipping_address.country) || ShippingCountry.find_by_country('WORLDWIDE')
      shipping_country.present?
    end
  end

  def has_no_email?
    user_id.blank? && email.blank?
  end

  def mark_as_reminded
    self.reminded = true
    self.reminded_at = Time.now
    self.save!
  end

  private

    def validate_coupon_code_exists
      begin
        coupon = Coupon.active.find_by_code!(coupon_code)
        self.coupon_amount = coupon.amount
        self.coupon_percentage = coupon.percentage
      rescue
        # if coupon not valid, then remove it from cart
        self.coupon_code = nil
        self.coupon_amount = nil
        self.coupon_percentage = nil
      end
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	def show
    @currency = session[:currency]
	end

  def update
    @cart.update_attributes(safe_params)
    @cart.calculate

    redirect_to cart_url
  end

  def apply_coupon
    @cart.apply_coupon(params[:coupon_code])
    redirect_to cart_url
  end

  def remove_coupon
    @cart.remove_coupon
    redirect_to cart_url
  end

	def destroy
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to cart_url }
    end
	end

  def checkout
    @cart = current_cart

    if @cart.items.empty?
      redirect_to products_url, notice: "#{t 'theme.cart.is_empty'}."
      return
    end
  end

  def continue
    # save user address
    @cart = current_cart

    if @cart.update_attributes(safe_params)
      if @cart.shipping_availability?
        redirect_to new_order_url
      else
        redirect_to checkout_cart_url, alert: "#{t 'theme.cart.no_shipping_in_country', default: 'Sorry, we cannot proceed with your order as we currently do not ship to'} #{Country[@cart.shipping_address.country].name}"
      end
    else
      render :checkout
    end
  end

  private

    def safe_params
      params.require(:cart).permit(:coupon_code, :email, :first_name, :last_name, :billing_address_attributes, :shipping_address_attributes, items_attributes: [:id, :quantity, :price],
                                   billing_address_attributes: [:id, :full_name, :address1, :address2, :city, :country, :postal_code, :province, :also_shipping_address],
                                   shipping_address_attributes: [:id, :full_name, :address1, :address2, :city, :country, :postal_code, :province] )
    end

end

app/controllers/reseller/carts_controller.rb
class Reseller::CartsController < Reseller::BaseController
  set_tab :orders

  def new
    @cart = @current_user.carts.find(session[:reseller_cart_id])

    unless @cart.items.any?
      # @products = Product.visibles.includes(:variants).order('name')
      @products = Collection.find_by(name: 'revendeur').products.order('position')
      @products.each do |product|
        @cart.items.build(
          variant_id: product.master.id,
          quantity: 0,
          price: product.master.reseller_price || product.master.price
        )
        if product.variants.any?
          product.variants.each do |variant|
            @cart.items.build(
              variant_id: variant.id,
              quantity: 0,
              price: variant.reseller_price || variant.price
            )
          end
        end
      end
    end
  end

  def update
    @cart = @current_user.carts.find(session[:reseller_cart_id])
    respond_to do |format|
      @cart.billing_address.bypass_validation = true
      @cart.shipping_address.bypass_validation = true
      if @cart.update_attributes(safe_params)

        @cart.items.each do |item|
          item.update_attribute('price', item.variant.reseller_price || item.variant.price)
        end

        @cart.calculate
        format.html { redirect_to new_reseller_order_url }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def destroy
    @current_user.carts.find(session[:reseller_cart_id]).destroy
    respond_to do |format|
      format.html { redirect_to reseller_orders_url }
    end
  end

  private

    def safe_params
      params.require(:cart).permit(items_attributes: [:id, :quantity, :variant_id])
    end
end

app/views/carts/_summary.html.erb
<table id="cart" class="table table-striped">
  <tr>
    <th><%= t 'theme.item' %></th>
    <th><%= t 'theme.quantity' %></th>
    <th><%= t 'theme.unit_price' %></th>
    <th><%= t 'theme.full_price' %></th>
  </tr>
  <% @cart.items.each do |item| %>
    <tr>
      <td><%= item.variant.cart_name %></td>
      <td><%= item.quantity %></td>
      <td><%= number_to_currency(item.price) %></td>
      <td><%= number_to_currency(item.quantity * item.price) %></td>
    </tr>
  <% end %>
  <tr class="total">
    <td colspan="3"><%= t 'theme.subtotal' %></td>
    <td><span id="subtotal" data-value="<%= @cart.subtotal %>"><%= number_to_currency @cart.subtotal %></span></td>
  </tr>
  <% if @cart.discount > 0 %>
  <tr class="total">
    <td colspan="3"><%= t 'theme.discount' %></td>
    <td><span id="discount" data-value="<%= @cart.discount %>"><%= number_to_currency(-@cart.discount) %></span></td>
  </tr>
  <% end %>
  <% if @cart.tax_amount > 0 %>
  <tr class="total">
    <td colspan="3"><%= @cart.tax_name.presence || "#{t 'theme.tax'}" %> (<%= number_to_percentage @cart.tax_rate, precision: 0 %>)</td>
    <td><span id="tax" data-value="<%= @cart.tax_amount %>"><%= number_to_currency @cart.tax_amount %></span></td>
  </tr>
  <% end %>
  <tr class="total" style="display:<%= @cart.try_with_default(:shipping, 0) > 0 ? '' : 'none' %>" id="shipping-row">
    <td colspan="3"><%= t 'theme.shipping.title' %></td>
    <td><span id="shipping" data-value="<%= @cart.try_with_default(:shipping, 0) %>"><%= number_to_currency @cart.try_with_default(:shipping, 0) %></span></td>
  </tr>
  <tr class="total">
    <td colspan="3"><%= t 'theme.total' %></td>
    <td><span id="total" data-value="<%= @cart.total %>"><%= number_to_currency @cart.total %></span></td>
  </tr>
</table>

<p class="alert"><i class="icomoon icon-lock"></i> <%= t 'theme.checkout.secure_connection' %>.</p>

app/views/carts/checkout.html.erb
<%= content_for :body_id do %>checkout<% end %>

<%= page_title("#{t 'theme.checkout.title'}") %>

<% if logged_in? %>
  <section id="order-addreses">
    <%= simple_form_for(@cart, url: continue_cart_path, method: :post, html: {class: 'form-horizontal'}) do |f| %>
      <%= f.error_notification %>
      <%
        default_billing_address = current_user.orders.try(:last).try(:billing_address) || current_user.addresses.try(:first)
        default_shipping_address = current_user.orders.try(:last).try(:shipping_address) || current_user.addresses.try(:first)
        also_shipping_address = default_billing_address && default_billing_address.same_as(default_shipping_address)
        @cart.build_billing_address(also_shipping_address: also_shipping_address).copy(default_billing_address) unless @cart.billing_address
        @cart.build_shipping_address unless @cart.shipping_address
        @cart.shipping_address.copy(default_shipping_address) unless @cart.billing_address.also_shipping_address
      %>

      <div class="row-fluid">
        <div id="billing-address" class="span6">
          <h4 class="section-helper"><%= t 'theme.billing_address' %></h4>
          <% if current_user.addresses.any? %>
            <div class="control-group">
              <label class="control-label"><%= t 'theme.select_address' %></label>
              <div class="controls"><%= select_tag :billing_address, options_for_select([''] + current_user.addresses.map{|a| a.display_name(', ')}, @cart.billing_address.try(:display_name, ', ')), name: nil %>
              </div>
            </div>
          <% end %>
          <%= f.fields_for :billing_address do |ba| %>
            <div id="billing_address_fields" class="form-horizontal">
              <%= ba.input :full_name, required: true, input_html: {value: current_user.full_name} %>
              <%= ba.input :address1, required: true %>
              <%= ba.input :address2 %>
              <%= ba.input :postal_code, required: true %>
              <%= ba.input :city, required: true %>
              <%= ba.input :country, collection: all_countries,  required: true %>
              <%= ba.input :province, collection: province_options, as: :grouped_select, group_method: :last, group_label_method: :first, wrapper_html: {id: 'billing_province', style: "display:#{['US', 'CA'].include?(ba.object.country) ? 'block': 'none'};"} %>

              <div class="checkbox inline nolabel">
                <label> <%= ba.check_box :also_shipping_address, id: 'also_shipping_address' %>
                 <%= t 'theme.shipping_and_billing_are_the_same' %>
                </label>
              </div>
            </div>
          <% end %>
        </div>

        <div id="shipping-address" class="span6">
          <h4 class="section-helper"><%= t 'theme.shipping_address' %></h4>
          <div id="shipping_address_fields" class="form-horizontal" style="display: <%= @cart.billing_address.also_shipping_address ? 'none' : 'block' %>;">
            <% if current_user.addresses.any? %>
              <div class="control-group">
                <label class="control-label"><%= t 'theme.select_address' %></label>
                <div class="controls"><%= select_tag :shipping_address, options_for_select([''] + current_user.addresses.map{|a| a.display_name(', ')}, @cart.shipping_address.try(:display_name, ', ')), name: nil %>
                </div>
              </div>
            <% end %>
            <%= f.fields_for :shipping_address do |sa| %>
              <%= sa.input :full_name, required: true %>
              <%= sa.input :address1, required: true %>
              <%= sa.input :address2 %>
              <%= sa.input :postal_code, required: true %>
              <%= sa.input :city, required: true %>
              <%= sa.input :country, collection: all_countries, required: true %>
              <%= sa.input :province, collection: province_options, as: :grouped_select, group_method: :last, group_label_method: :first, wrapper_html: {id: 'shipping_province', style: "display:#{['US', 'CA'].include?(sa.object.country) ? 'block': 'none'};"} %>
            <% end %>
          </div>
          <div id="same-address" class="alert alert-info" style="display: <%= @cart.billing_address.also_shipping_address ? 'block' : 'none' %>;">
            <%= t 'theme.same_as_billing_address' %>
          </div>
        </div>
      </div>
      <p><%= f.button :submit, "#{t 'theme.cart.continue'}", class: "btn btn-primary nolabel" %></p>
      <% end %>
  </section>
<% else %>
  <div class="row-fluid">
    <section id="login" class="span6">
      <h3><%= t 'theme.login' %></h3>
      <%= simple_form_for(:session, url: sessions_path, method: :post, html: {class: "form-horizontal"}) do |f| %>
        <%= f.error_notification %>
        <%= hidden_field_tag :checkout, '1' %>

        <%= f.input :email %>
        <%= f.input :password %>

        <p id="remember-control" class="nolabel">
          <%= check_box_tag :remember_me %> <%= t 'theme.remember_me' %>
        </p>
        <%= f.button :submit, class: "btn nolabel" %>
      <% end %>

      <p class="nolabel" style="margin-top:20px;"><%= link_to "#{t 'theme.passwords.forgot'}", new_password_path %></p>
    </section>

    <section id="signup" class="span6">
      <h3><%= t 'theme.register' %></h3>

      <%= simple_form_for(User.new, url: registrations_path, html: {class: "form-horizontal"}) do |f| %>
        <%= f.error_notification %>
        <%= hidden_field_tag :checkout, '1' %>

        <%= f.input :email %>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :password, hint: false %>
        <%= f.input :password_confirmation, required: true %>

        <%= f.button :submit, class: "btn nolabel" %>
      <% end %>
    </section>
  </div>

  <section id="checkout-as-guest">
    <h3><%= t 'theme.checkout.as_guest' %></h3>

    <%= simple_form_for(@cart, url: continue_cart_path, method: :post, html: {class: 'form-horizontal'}) do |f| %>
      <%= f.error_notification %>

      <% 
        @cart.build_billing_address(also_shipping_address: true) unless @cart.billing_address
        @cart.build_shipping_address unless @cart.shipping_address
      %>

      <h4 class="section"><%= t 'theme.checkout.your_details' %></h4>
      <%= f.input :email, required: true %>
      <%= f.input :first_name, required: true %>
      <%= f.input :last_name, required: true %>

      <div class="row-fluid">
        <div id="billing-address" class="span6">
          <h4 class="section-helper"><%= t 'theme.billing_address' %></h4>
          <%= f.fields_for :billing_address do |ba| %>
            <div id="billing_address_fields" class="form-horizontal">
              <%= ba.input :full_name, required: true %>
              <%= ba.input :address1, required: true %>
              <%= ba.input :address2 %>
              <%= ba.input :postal_code, required: true %>
              <%= ba.input :city, required: true %>
              <%= ba.input :country, required: true %>
              <%= ba.input :province, collection: province_options, as: :grouped_select, group_method: :last, group_label_method: :first, wrapper_html: {id: 'billing_province', style: "display:#{['US', 'CA'].include?(ba.object.country) ? 'block': 'none'};"} %>
              <div class="checkbox inline nolabel">
                <label> <%= ba.check_box :also_shipping_address, id: 'also_shipping_address' %>
                 <%= t 'theme.shipping_and_billing_are_the_same' %>
                </label>
              </div>
            </div>
          <% end %>
        </div>

        <div id="shipping-address" class="span6">
          <h4 class="section-helper"><%= t 'theme.shipping_address' %></h4>
          <div id="shipping_address_fields" class="form-horizontal" style="display: <%= @cart.billing_address.also_shipping_address ? 'none' : 'block' %>;">
            <%= f.fields_for :shipping_address do |sa| %>
              <%= sa.input :full_name, required: true %>
              <%= sa.input :address1, required: true %>
              <%= sa.input :address2 %>
              <%= sa.input :postal_code, required: true %>
              <%= sa.input :city, required: true %>
              <%= sa.input :country, required: true %>
              <%= sa.input :province, collection: province_options, as: :grouped_select, group_method: :last, group_label_method: :first, wrapper_html: {id: 'shipping_province', style: "display:#{['US', 'CA'].include?(sa.object.country) ? 'block': 'none'};"} %>
            <% end %>
          </div>
          <div id="same-address" class="alert alert-info" style="display: <%= @cart.billing_address.also_shipping_address ? 'block' : 'none' %>;">
            <%= t 'theme.same_as_billing_address' %>
          </div>
        </div>
      </div>  
      <p><%= f.button :submit, "#{t 'theme.cart.continue'}", class: "btn nolabel" %></p>
    <% end %>
  </section>
<% end %>  

<script type="text/javascript" charset="utf-8">
  $(function() {
    <% if logged_in? %>
      var addresses = <%= raw current_user.addresses.to_json %>;
    <% else %>  
      var addresses = null;
    <% end %>
    Cart.checkout(addresses);
  });
</script>

app/views/carts/show.html.erb
<%= content_for :body_id do %>cart<% end %>
<%= page_title("#{t 'theme.cart.title'}") %>

<% if @cart.items.any? %>
  <%= form_for @cart, url: cart_path do |f| %>
  	<table id="cart" class="table table-striped">
  	  <tr>
        <th></th>
  	    <th><%= t 'theme.item' %></th>
  	    <th><%= t 'theme.quantity' %></th>
        <th><%= t 'theme.unit_price' %></th>
  	    <th><%= t 'theme.subtotal' %></th>
  	  </tr>

      <%= f.fields_for :items do |ff| %>
        <% item = ff.object %>
  	    <tr>
          <td><%= link_to "#{t 'theme.cart.remove'}", cart_line_item_path(item), method: :delete %></td>
  	      <td><%= image_tag(item.variant.product.pictures.first.upload.url(:thumb), size: "38x38") if item.variant.product.pictures.any? %> <%= item.variant.cart_name %></td>
  	      <td><%= ff.number_field :quantity, class: 'input-mini' %></td>
          <td><%= price_with_currency(item.price, @currency) %></td>
  	      <td><%= price_with_currency(item.quantity * item.price, @currency) %></td>
  	    </tr>
      <% end %>
  	</table>

    <div id="cart-actions" class="row-fluid">
      <%= link_to "#{t 'theme.cart.continue'}", checkout_cart_path, class: "btn btn-success fr" %>
      <%= f.submit data: {disable_with: "#{t 'theme.updating'}"}, class: 'btn fr' %>
    </div>
  <% end %>

  <% if @cart.coupon_applied? %>
    <%= t 'theme.coupon_code' %> <b>"<%= @cart.coupon_code %>"</b> <%= t 'theme.was_applied' %>. <%= link_to "#{t 'theme.cart.remove'}", remove_coupon_cart_path, method: :post %>
  <% else %>
    <%= form_tag apply_coupon_cart_path, class: 'form-inline' do %>
      <%= label_tag :coupon_code, "#{t 'theme.coupon_code'}" %>
      <%= text_field_tag :coupon_code, @cart.coupon_code %>
      <%= submit_tag "#{t 'theme.apply_coupon'}", data: {disable_with: "#{t 'theme.apply_coupon'}"}, class: 'btn' %>
    <% end %>
  <% end %>

  <table id="cart-totals" style="float:right;" class="span6">
    <tr>
      <td><%= t 'theme.subtotal' %></td>
      <td><%= price_with_currency(@cart.subtotal, @currency) %></td>
    </tr>
    <% if @cart.discount > 0 %>
      <tr>
        <td><%= t 'theme.discount' %></td>
        <td><%= price_with_currency(-@cart.discount, @currency) %></td>
      </tr>
    <% end %>
    <tr id="shipping" style="display:none;">
      <td><%= t 'theme.estimated_shipping' %></td>
      <td><span id="shipping-price"></span></td>
    </tr>
  </table>

  <% if ShippingCountry.count > 0 %>
    <div id="shipping_calculator" class="row-fluid">
      <h3><%= t 'theme.shipping_rate.calculator' %></h3>
      <%= simple_form_for :shipping, url: search_shippings_path, remote: true do |f| %>
        <div class="row-fluid">
          <div class="span3">
            <%= f.hidden_field :subtotal, value: @cart.subtotal %>
            <%= f.input :country, collection: all_countries, input_html: {class: 'input-block-level'} %>
          </div>
          <div class="span3" style="margin-left:0;">
            <div class="control-group string optional">
              <label class="string optional control-label" for="shipping_calculate">&nbsp;</label>
              <div class="controls">
                <%= f.submit "#{t 'theme.cart.calculate'}", class: 'btn', data: {disable_with: "#{t 'theme.calculating'}"}, style: 'margin-left:0;' %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <div id="shipping-rate-feedback" style="display:none;"></div>
    </div>
  <% end %>
<% else %>
  <p class="alert"><%= t 'theme.cart.is_empty' %>. <%= link_to "#{t 'theme.products.browse'}", products_path %></p>
<% end %>