config/routes.rb
require 'api_constraints'
require 'sidekiq/web'
require 'admin_constraint'

Bento::Application.routes.draw do

  # ============================================================
  # USER ROUTES
  # ============================================================
  delete 'logout'            => 'sessions#destroy',     as: "logout"
  get 'login'                => 'sessions#new',         as: "login"
  get 'signup'               => 'registrations#new',    as: "signup"
  get 'profile'              => 'registrations#edit',   as: "profile"
  post 'profile'             => 'registrations#update', as: "update_profile"
  get 'paswords/:token/edit' => 'passwords#edit',       as: "change_password"
  resource :password, only: [:new, :create, :edit, :update]
  resources :registrations, except: [:index, :show, :destroy]
  resources :sessions

  # ============================================================
  # API ROUTES
  # ============================================================
  get '/stripe/callback'    => 'stripe#callback'
  get 'api/google_shopping' => 'api#google_shopping'
  get 'api/sitemap'         => 'api#sitemap'
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :products, only: [:index, :show]
    end
  end

  # ============================================================
  # ADMIN ROUTES
  # ============================================================
  scope module: 'admin', path: 'adm1nistr8tion', as: 'admin' do
    mount Sidekiq::Web => 'sidekiq', constraints: AdminConstraint.new
    root to: 'dashboard#show', as: :dashboard
    get 'search', to: 'dashboard#search',   as: :search
    get 'audit',  to: 'audit_trails#index', as: 'audit'
    resource :stock, only: [:show, :update], path: 'stocks', as: 'stocks'
    resources :articles
    resources :categories, only: [:index, :edit, :update, :destroy]
    resources :clients, only: [:index, :show] do
      get 'export', on: :collection
    end
    resources :coupons, except: :show
    resources :pages
    resources :taxes
    scope "/shipping" do
      root to: 'shipping_countries#index', as: :shipping
      resources :shipping_countries, except: [:index, :show]
    end

    resources :collections do
      member do
        post 'sort_products'
        post 'add_products'
        post 'remove_products'
      end
    end

    resources :resellers, only: [:index, :show] do
      get 'catalogue', on: :collection
      member do
        post :toggle_reseller_status
      end
    end

    resources :products do
      resource :options, only: [:edit, :update], as: :options
      resources :variants, only: [:destroy]
      collection do
        put 'feature'
        get 'export'
      end
      resources :pictures do
        collection do
          post :sort
        end
      end
    end

    resources :product_reviews, only: [:index, :show] do
      member do
        post :toggle_product_review_status
      end
    end

    resource :settings, only: [:show, :update] do
      delete :remove_logo
    end

    resource :reports do
      collection do
        get 'sales'
        get 'monthly_sales'
        get 'orders'
      end
    end

    resources :users, except: [:show, :edit, :update] do
      post :toggle_status, on: :member
    end

    resources :orders, only: [:index, :show, :edit, :update] do
      put 'print', on: :collection
      get 'abandoned', on: :collection
      member do
        post 'mark_as_shipped'
        post 'cancel'
      end
    end
  end

  # ============================================================
  # RESELLER ROUTES
  # ============================================================
  scope module: 'reseller', path: 'reseller', as: 'reseller' do
    root to: 'dashboard#show', as: :dashboard
    resources :carts, only: [:new, :update, :destroy]
    resources :orders, only: [:index, :show, :new, :create]
    resources :products do
      resource :options, only: [:edit, :update], as: :options
    end
  end

  # ============================================================
  # PUBLIC ROUTES
  # ============================================================
  post 'language/set_to_english'
  post 'language/set_to_french'
  get 'application/users' # used for dynamic caching only

  scope '/blog' do
    get '/', controller: 'articles', action: 'index', as: 'blog'
    get '/:slug'    => "articles#show",  as: 'article'
    get '/tag/:tag' => "articles#index", as: 'tag'
  end

  resource :cart, except: [:new, :create, :edit] do
    member do
      post :apply_coupon
      post :remove_coupon
      get :checkout
      post :continue
    end
    resources :line_items
  end
  resources :line_items, only: [:create, :update]

  resources :orders, only: [:index, :new, :create, :show]
  resources :tags, only: :index
  resources :categories, only: :index
  resources :suppliers, only: :index
  resources :product_reviews, only: :create
  resources :products, only: [:index, :show] do
    get :search, on: :collection
  end
  resources :shippings, only: [] do
    post :search, on: :collection
  end
  resource :reseller_request, only: :create
  resource :contact, only: [:show, :create]
  
  get '/category/:category', to: 'products#index',        as: 'category'
  get '/collection/:slug',   to: 'collections#show',      as: 'collection'
  get 'become_reseller',     to: 'pages#become_reseller', as: "become_reseller"
  get 'user_info',           to: 'pages#user_info'
  get 'set_currency',        to: 'application#set_currency'
  get 'get_total',           to: 'application#get_total'
  get '/:slug',              to: 'pages#show',            as: 'page'

  root :to => 'pages#home'
end

app/models/collection.rb
class Collection < ActiveRecord::Base

  # FRIENDLY ID
  # ------------------------------------------------------------------------------------------------------
  extend FriendlyId
  friendly_id :slug, use: [:slugged, :history]
  include Sluggable
  include PgSearch


  # SEARCH
  # ------------------------------------------------------------------------------------------------------
  multisearchable :against => :name
  pg_search_scope :search_by_keyword,
                  :against => [:name],
                  :using => {
                    :tsearch => {
                      :prefix => true # match any characters
                    }
                  },
                  :ignoring => :accents


  # ASSOCIATIONS
  # ------------------------------------------------------------------------------------------------------
  has_many :collection_products, dependent: :destroy
  has_many :products, through: :collection_products


  # ATTRIBUTES
  # ------------------------------------------------------------------------------------------------------
  store :meta_tag, accessors: [:seo_title, :seo_description]


  # CALLBACKS
  # ------------------------------------------------------------------------------------------------------
  before_save :format_slug


  # SCOPES
  # ------------------------------------------------------------------------------------------------------
  scope :visibles, -> { where(visible: true) }
  scope :private,  -> { where(visible: false) }


  # VALIDATIONS
  # ------------------------------------------------------------------------------------------------------
  validates_presence_of :name, :slug
  validates_uniqueness_of :name, :slug

end

app/controllers/admin/collections_controller.rb
class Admin::CollectionsController < Admin::BaseController
  before_action :set_collection, only: [:edit, :update, :destroy, :add_products, :remove_products, :sort_products]
  set_tab :collections
  cache_sweeper :collection_sweeper

  def index
    @collections = Collection.order('created_at DESC')
  end

  def show
    @collection = Collection.includes(:products).friendly.find(params[:id])
    if @collection.products.any?
      @products = Product.exclude_products(@collection.products.pluck(:product_id)).order('name')
    else
      @products = Product.order('name')
    end
  end

  def new
    @collection = Collection.new
  end

  def edit
  end

  def create
    @collection = Collection.new(safe_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to admin_collection_url(@collection), notice: 'Collection was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    respond_to do |format|
      if @collection.update_attributes(safe_params)
        format.html { redirect_to admin_collection_url(@collection), notice: 'Collection was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to admin_collections_url, notice: 'Collection was successfully deleted.' }
    end
  end

  def sort_products
    params[:product].each_with_index do |id, index|
      CollectionProduct.where(product_id: id, collection_id: @collection.id).update_all(position: index+1)
    end
    render nothing: true
  end

  def add_products
    @collection.products << Product.find(params[:product_id])
    @products = Product.exclude_products(@collection.products.pluck(:product_id)).order('name')

    respond_to do |format|
      format.js
    end
  end

  def remove_products
    @collection.products.delete(Product.find(params[:product_id]))

    if @collection.products.any?
      @products = Product.exclude_products(@collection.products.pluck(:product_id)).order('name')
    else
      @products = Product.order('name')
    end

    respond_to do |format|
      format.js
    end
  end

  private

    def set_collection
      @collection = Collection.friendly.find(params[:id])
    end

    def safe_params
      params.require(:collection).permit(:description, :name, :visible, :slug, :seo_title, :seo_description)
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end

    def sort_column
      Collection.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_filter(only: [:show]) { @page_caching = true }
  caches_page :show

	def show
    @collection = Collection.friendly.includes(products: [:master]).find(params[:slug])
    @page_title       = "#{@collection.seo_title.present? ? @collection.seo_title : @collection.name} | #{t 'theme.site_name'}"
    @page_description = @collection.seo_description
    @products = @collection.products.visibles.order('position').page(params[:page]).per(12)
    @currency = session[:currency]

    if !@collection.visible?
      raise ActionController::RoutingError.new('Not Found')
    elsif request.path != "/collection/#{@collection.slug}"
      return redirect_to "/collection/#{@collection.slug}", status: :moved_permanently
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

end

app/views/admin/collections/_form.html.erb
<%= simple_form_for([:admin, @collection], html: {class: 'form-horizontal'}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, input_html: {class: 'span12'}, placeholder: "Summer collection, Under $50, Staff picks..." %>
    <%= f.input :slug, input_html: {class: 'span12'} %>
    <%= f.input :visible, as: :radio_buttons, item_wrapper_class: 'inline' %>
    <%= f.input :description %>

    <%= subsection_title("SEO") %>
    <%= render 'admin/meta_tags/form', f: f %>
  </div>
  <div class="form-actions">
    <%= submit_or_cancel(f) %>
  </div>
<% end %>

app/views/admin/collections/_from.html.erb
<% @products.each do |product| %>
  <%= content_tag_for :li, product do %>
    <%= image_tag(product.pictures.first.upload.url(:thumb), alt: "#{product.pictures.first.name}", style: "height:26px; width:26px;") if product.pictures.any? %>
    <%= link_to(add_products_admin_collection_path(@collection, product_id: product.id), method: :post, remote: true) do %>
      <%= "#{truncate(product.name, length: 40)}" %> <i class="icon-chevron-right"> </i>
    <% end %>
  <% end %>
<% end %>

app/views/admin/collections/_to.html.erb
<% if @collection.products.any? %>
  <% @collection.products.order('position').each do |product| %>
    <%= content_tag_for :li, product do %>
      <%= image_tag(product.pictures.first.upload.url(:thumb), alt: "#{product.pictures.first.name}", style: "height:26px; width:26px;") if product.pictures.any? %>
      <%= product.name %> <%= icon_link_to "", remove_products_admin_collection_path(@collection, product_id: product.id), method: :post, remote: true, icon: 'remove', class: "remove fr" %></span>
    <% end %>
  <% end %>
<% else %>
 <p class="alert">Add Products to the collection.<br>
  Products can be re-ordered by dragging and dropping.</p>
 </p>
<% end %>

app/views/admin/collections/add_products.js.erb
$('#products-list').html('<%= j(render("/admin/collections/from")) %>');
$("#collection-products").html('<%= j(render("/admin/collections/to")) %>');

app/views/admin/collections/edit.html.erb
<%= page_title("#{t 'collections.edit'}") %>

<%= render 'form' %>

app/views/admin/collections/index.html.erb
<%= page_title("#{t 'collections.title'}") do %>
  <%= icon_button_link_to "#{t 'collections.new'}", new_admin_collection_path, level: 'primary', icon: 'plus', white: true, class: 'fr' %>
<% end %>

<% if @collections.present? %>
  <table id="collections" class="table table-striped">
    <tr>
      <th><%= "#{t 'name'}" %></th>
      <th>Slug</th>
      <th><%= "#{t 'products.title'}" %></th>
      <th style="min-width:100px;"></th>
    </tr>
    
    <% @collections.each do |coll| %>
      <tr>
        <td><%= link_to coll.name, admin_collection_path(coll) %> <%= status_tag "#{t 'private'}" if !coll.visible? %></td>
        <td><%= coll.slug %></td>
        <td><%= pluralize(coll.products.length, "#{t 'product'}") %></td>
        <td><%= icon_button_link_to "#{t 'edit'}", edit_admin_collection_path(coll), icon: 'pencil', size: 'small' %></td>
      </tr>
    <% end %>
  </table>

<% else %>
  <div class="alert"><%= t 'collections.none' %>.</div>
<% end %>

app/views/admin/collections/new.html.erb
<%= page_title("#{t 'collections.new'}") %>

<%= render 'form' %>

<script type="text/javascript">
  $('#collection_name').one('change', function() {
    $('#collection_slug').val($(this).val().replace(/\s+/g, '-').toLowerCase());
  });
</script>

app/views/admin/collections/remove_products.js.erb
$('#products-list').html('<%= j(render("/admin/collections/from")) %>');
$("#collection-products").html('<%= j(render("/admin/collections/to")) %>');

app/views/admin/collections/show.html.erb
<%= page_title(@collection.name) do %>
  <%= status_tag("#{t 'private'}") if !@collection.visible %>
  <%= icon_button_link_to "#{t 'destroy'}", admin_collection_path(@collection), method: :delete, data: {confirm: "#{t 'are_you_sure'}"}, level: 'danger', icon: 'remove', white: true, class: "fr" %>
  <%= icon_button_link_to "#{t 'edit'}", edit_admin_collection_path(@collection), level: 'primary', icon: 'pencil', white: true, class: "fr" %>
<% end %>

<p>
  <b>URL:</b>
  <%= link_to "#{collection_url(@collection.slug)}", collection_url(@collection.slug), 'data-no-turbolink'=>true %>
</p>

<%= markdown(@collection.description) %>

<%= subsection_title("#{t 'products.title'}") %>

<div class="row-fluid">
	<% if Product.count > 0 %>
	  <ul id="products-list" class="span5">
		  <%= render 'admin/collections/from' %>
		</ul>

	  <ul id="collection-products" class="span7" data-update-url="<%= sort_products_admin_collection_url %>">
		  <%= render 'admin/collections/to' %>
		</ul>
	<% else %>
	  <p class="alert">Create products first so you can add to them to the collection.</p>
	<% end %>
</div>