config/routes.rb
require 'api_constraints'
require 'sidekiq/web'
require 'admin_constraint'

Bento::Application.routes.draw do

  # ============================================================
  # USER ROUTES
  # ============================================================
  delete 'logout'            => 'sessions#destroy',     as: "logout"
  get 'login'                => 'sessions#new',         as: "login"
  get 'signup'               => 'registrations#new',    as: "signup"
  get 'profile'              => 'registrations#edit',   as: "profile"
  post 'profile'             => 'registrations#update', as: "update_profile"
  get 'paswords/:token/edit' => 'passwords#edit',       as: "change_password"
  resource :password, only: [:new, :create, :edit, :update]
  resources :registrations, except: [:index, :show, :destroy]
  resources :sessions

  # ============================================================
  # API ROUTES
  # ============================================================
  get '/stripe/callback'    => 'stripe#callback'
  get 'api/google_shopping' => 'api#google_shopping'
  get 'api/sitemap'         => 'api#sitemap'
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :products, only: [:index, :show]
    end
  end

  # ============================================================
  # ADMIN ROUTES
  # ============================================================
  scope module: 'admin', path: 'adm1nistr8tion', as: 'admin' do
    mount Sidekiq::Web => 'sidekiq', constraints: AdminConstraint.new
    root to: 'dashboard#show', as: :dashboard
    get 'search', to: 'dashboard#search',   as: :search
    get 'audit',  to: 'audit_trails#index', as: 'audit'
    resource :stock, only: [:show, :update], path: 'stocks', as: 'stocks'
    resources :articles
    resources :categories, only: [:index, :edit, :update, :destroy]
    resources :clients, only: [:index, :show] do
      get 'export', on: :collection
    end
    resources :coupons, except: :show
    resources :pages
    resources :taxes
    scope "/shipping" do
      root to: 'shipping_countries#index', as: :shipping
      resources :shipping_countries, except: [:index, :show]
    end

    resources :collections do
      member do
        post 'sort_products'
        post 'add_products'
        post 'remove_products'
      end
    end

    resources :resellers, only: [:index, :show] do
      get 'catalogue', on: :collection
      member do
        post :toggle_reseller_status
      end
    end

    resources :products do
      resource :options, only: [:edit, :update], as: :options
      resources :variants, only: [:destroy]
      collection do
        put 'feature'
        get 'export'
      end
      resources :pictures do
        collection do
          post :sort
        end
      end
    end

    resources :product_reviews, only: [:index, :show] do
      member do
        post :toggle_product_review_status
      end
    end

    resource :settings, only: [:show, :update] do
      delete :remove_logo
    end

    resource :reports do
      collection do
        get 'sales'
        get 'monthly_sales'
        get 'orders'
      end
    end

    resources :users, except: [:show, :edit, :update] do
      post :toggle_status, on: :member
    end

    resources :orders, only: [:index, :show, :edit, :update] do
      put 'print', on: :collection
      get 'abandoned', on: :collection
      member do
        post 'mark_as_shipped'
        post 'cancel'
      end
    end
  end

  # ============================================================
  # RESELLER ROUTES
  # ============================================================
  scope module: 'reseller', path: 'reseller', as: 'reseller' do
    root to: 'dashboard#show', as: :dashboard
    resources :carts, only: [:new, :update, :destroy]
    resources :orders, only: [:index, :show, :new, :create]
    resources :products do
      resource :options, only: [:edit, :update], as: :options
    end
  end

  # ============================================================
  # PUBLIC ROUTES
  # ============================================================
  post 'language/set_to_english'
  post 'language/set_to_french'
  get 'application/users' # used for dynamic caching only

  scope '/blog' do
    get '/', controller: 'articles', action: 'index', as: 'blog'
    get '/:slug'    => "articles#show",  as: 'article'
    get '/tag/:tag' => "articles#index", as: 'tag'
  end

  resource :cart, except: [:new, :create, :edit] do
    member do
      post :apply_coupon
      post :remove_coupon
      get :checkout
      post :continue
    end
    resources :line_items
  end
  resources :line_items, only: [:create, :update]

  resources :orders, only: [:index, :new, :create, :show]
  resources :tags, only: :index
  resources :categories, only: :index
  resources :suppliers, only: :index
  resources :product_reviews, only: :create
  resources :products, only: [:index, :show] do
    get :search, on: :collection
  end
  resources :shippings, only: [] do
    post :search, on: :collection
  end
  resource :reseller_request, only: :create
  resource :contact, only: [:show, :create]
  
  get '/category/:category', to: 'products#index',        as: 'category'
  get '/collection/:slug',   to: 'collections#show',      as: 'collection'
  get 'become_reseller',     to: 'pages#become_reseller', as: "become_reseller"
  get 'user_info',           to: 'pages#user_info'
  get 'set_currency',        to: 'application#set_currency'
  get 'get_total',           to: 'application#get_total'
  get '/:slug',              to: 'pages#show',            as: 'page'

  root :to => 'pages#home'
end

app/controllers/admin/reports_controller.rb
# encoding: utf-8

class Admin::ReportsController < Admin::BaseController
  helper_method :sort_column, :sort_direction

  def monthly_sales
    set_tab :monthly_sales_report
    @date = params[:month] ? Date.strptime(params[:month], "%Y-%m") : Date.today
    @orders = Order.where(created_at: (@date).beginning_of_month..(@date).end_of_month).order('created_at DESC')

    respond_to do |format|
      format.html
      format.json { render json: @orders }
    end
  end

  def sales
    set_tab :sales_report
    @year = params[:year].blank? ? Date.today.year : params[:year].to_i
    @years = AuditYear.all.map(&:year)
    @years << @year unless @years.include?(@year)
    @years = @years.sort
    @orders_months = Order.where(["EXTRACT(year from created_at) = ?", @year])
    @months = @orders_months.group_by{|orders| orders.created_at.month}
  end

  def orders
    set_tab :orders_report
    @search = Order.search(params[:q])
    @orders = @search.result.order('created_at DESC').page(params[:page]).per(15)

    respond_to do |format|
      format.html
      format.csv { 
        content = @orders.to_csv
        content = content.encode("UTF-8")
        send_data content, filename: "#{t 'orders.title'}.csv", type: 'text/csv; charset=utf-8; header=present'
      }
    end
  end

  private

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end

    def sort_column
      params[:sort].present? ? params[:sort] : "created_at"
    end

end

app/views/admin/reports/_orders.html.erb
<table id="orders" class="table table-striped">
  <tr>
    <th><%= sort_link @search, "code", "#" %></th>
    <th><%= sort_link @search, "completed", "#{t 'status.title'}" %></th>
    <th><%= sort_link @search, :user_id, "#{t 'client'}" %></th>
    <th><%= sort_link @search, :created_at, "#{t 'orders.date'}" %></th>
    <th><%= sort_link @search, "price", "#{t 'price'}" %></th>
  </tr>
  
  <% @orders.each do |order| %>
    <tr>
      <td><%= link_to order.code, admin_order_path(order) %></td>
      <td><%= status_tag(order.state, class: "state-#{order.state}") %></td>
      <td><%= order.client.full_name %></td>
      <td><%= l order.created_at, format: :long %></td>
      <td><%= number_to_currency(order.total, strip_insignificant_zeros: true) %></td>
    </tr>
  <% end %>
</table>

app/views/admin/reports/monthly_sales.html.erb
<%= page_title("#{t 'monthly_sales_report'}") %>

<h4 id="month_selector" style="margin-bottom:50px;">
  <%= link_to '&#x2190;'.html_safe, :month => (@date.beginning_of_month-1).strftime("%Y-%m") %>
  <%= I18n.localize(@date, format: '%B %Y') %>
  <%= link_to "&#x2192;".html_safe, :month => (@date.end_of_month+1).strftime("%Y-%m") %>
  <span id='go_to_current' class='fr'><%= link_to "#{t 'current_month'}", month: (Date.today.beginning_of_month).strftime('%Y-%m') %></span>
</h4>

<% if @orders.present? %>
  <div class="report_totals">
    <h2><%= t 'reports.total_sales_count' %>: <span><%= @orders.count %></span></h2>
    <h2><%= t 'reports.total_sales_amount' %>: <span><%= number_to_currency(@orders.map{|o| o.total}.sum, strip_insignificant_zeros: true) %></span></h2>
    <h2><%= t 'reports.total_sales_average' %>: <span><%= number_to_currency(@orders.map{|o| o.total}.sum, strip_insignificant_zeros: true) %></span></h2>
  </div>

<% else %>
  <div class="alert"><%= t 'orders.none' %>.</div>
<% end %>

app/views/admin/reports/orders.html.erb
<%= page_title("#{t 'reports.orders'}") %>

<div id="criteria_selection" class="well">
  <%= search_form_for @search, url: orders_admin_reports_path, html: {class: "form-inline form-search"} do |f| %>
    <%= f.text_field :created_at_casted_from, class: 'date_picker', style: 'max-width:90px;', placeholder: "#{t 'from_date'}" %>
    <%= f.text_field :created_at_casted_to, class: 'date_picker', style: 'max-width:90px;', placeholder: "#{t 'to_date'}" %>
    <%= f.text_field :client_first_name_cont, placeholder: "#{t 'first_name'}", class: 'span2' %>
    <%= f.text_field :client_last_name_cont, placeholder: "#{t 'last_name'}", class: 'span2' %>
    <%= f.text_field :client_email_matches, placeholder: "Email", class: 'span2' %>
    <%= f.text_field :coupon_code_matches, placeholder: "#{t 'coupons.code'}", style: 'max-width:100px;' %>
    <button class="btn" type="submit"><i class="icon-search"></i></button>
    <% if @orders.any? %>
      <button class="btn" type="submit" name="format" value="csv"><i class="icon-download-alt"></i></button>
    <% end %>
    <button class="btn" type="submit" name="" id="q_reset"><i class="icon-remove"></i></button>
  <% end %>
</div>

<% if @orders.present? %>
  <%= render "orders" %>
  <%= paginate @orders %>
<% else %>
  <div class="alert"><%= t 'orders.none' %>.</div>
<% end %>

app/views/admin/reports/sales.html.erb
<%= page_title("#{t 'sales_report'}") %>

<div id="years">
  <form action="" method="get" class="filter">
    <div class="inline-form">
      <%= select_tag :year, options_for_select(@years, @year), onchange: "$(this).closest('form').submit();", class: 'span2' %>
    </div>
  </form>
</div>

<% if @orders_months.any? %>
  <table class="table table-striped">
    <tr>
      <th></th>
      <% (1..12).each do |month| %>
        <th><%= I18n.t('date.abbr_month_names')[month] %></th>
      <% end %>
    </tr>
    <tr>
      <td><%= t 'reports.total_sales_count' %></td>
      <% (1..12).each do |month| %>
        <% orders = @months[month] %>
        <td><%= orders.size if orders %></td>
      <% end %>
    </tr>
    <tr>
      <td><%= t 'reports.total_sales_amount' %></td>
      <% (1..12).each do |month| %>
        <% orders = @months[month] %>
        <td><%= number_to_currency(orders.sum(&:total), strip_insignificant_zeros: true) if orders %></td>
      <% end %>
    </tr>
  </table>
<% else %>
  <div class="alert"><%= t 'orders.none' %>.</div>
<% end %>